version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '06:00'
      timezone: Japan
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    commit-message:
      prefix: 'chore(other): '
